on:
  push:
name: Test
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      run: |
        echo $GITHUB_EVENT_NAME
    - name: Report build to bugsnag
      uses: sazap10/bugsnag-builds-action@master
      if: github.event == "tag"
      env:
        BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
