on:
  push:
name: Test
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set version
      run: |
        echo ::set-env name=PUSH_TYPE::$(echo $GITHUB_REF | cut -d / -f 2)
        echo ::set-env name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: test
      run: |
        echo $PUSH_TYPE
        echo ${{ env.PUSH_TYPE }}
        echo $VERSION
        echo ${{ env.VERSION }}
    - name: Report build to bugsnag
      uses: sazap10/bugsnag-builds-action@master
      if: env.PUSH_TYPE == 'tags'
      env:
        BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
